// Export all logos from a single file

export { Logo as ChatGPTMcpLogo } from "./chatgpt-mcp/assets/logo";
export { Logo as CompaniesHouseLogo } from "./companies-house/assets/logo";
export { Logo as CopilotMcpLogo } from "./copilot-mcp/assets/logo";
export { Logo as CursorMcpLogo } from "./cursor-mcp/assets/logo";
export { Logo as FortnoxLogo } from "./fortnox/assets/logo";
export { Logo as GmailLogo } from "./gmail/assets/logo";
export { Logo as MakeMcpLogo } from "./make-mcp/assets/logo";
export { Logo as N8nMcpLogo } from "./n8n-mcp/assets/logo";
export { Logo as OpenCodeMcpLogo } from "./opencode-mcp/assets/logo";
export { Logo as OutlookLogo } from "./outlook/assets/logo";
export { Logo as PerplexityMcpLogo } from "./perplexity-mcp/assets/logo";
export { Logo as QuickBooksLogo } from "./quick-books/assets/logo";
export { Logo as RaycastMcpLogo } from "./raycast-mcp/assets/logo";
export { Logo as SlackLogo } from "./slack/assets/logo";
export { Logo as StripePaymentsLogo } from "./stripe-payments/assets/logo";
export { Logo as WhatsAppLogo } from "./whatsapp/assets/logo";
export { Logo as ZapierMcpLogo } from "./zapier-mcp/assets/logo";
