import { createHash } from "node:crypto";
import { escapeXml } from "../formatting";
import { getHmrcCtEnvironment, getHmrcCtRuntimeStatus } from "../runtime";
import type { Ct600Draft } from "../types";
import { renderCt600DraftBodyXml } from "./body";
import { encodeInlineXbrlDocumentForCtSubmission } from "./inline-xbrl";

function computeCt600DraftIrmark(bodyXmlWithoutIrmark: string) {
  return createHash("sha1").update(bodyXmlWithoutIrmark, "utf8").digest("base64");
}

function resolveHmrcCtSubmissionReference(companyUtr?: string | null) {
  return (
    getHmrcCtRuntimeStatus({
      utr: companyUtr ?? null,
    }).submissionReference ?? "MISSING-UTR"
  );
}

export function renderCt600DraftXml(
  draft: Ct600Draft,
  options?: {
    accountsAttachmentXhtml?: string;
    computationsAttachmentXhtml?: string;
  },
) {
  const environment = getHmrcCtEnvironment();
  const vendorId = process.env.HMRC_CT_VENDOR_ID ?? "0000";
  const productName = process.env.HMRC_CT_PRODUCT_NAME ?? "Tamias";
  const productVersion = process.env.HMRC_CT_PRODUCT_VERSION ?? "0.1.0-draft";
  const senderId = process.env.HMRC_CT_SENDER_ID ?? "DRAFT-SENDER-ID";
  const senderPassword = process.env.HMRC_CT_SENDER_PASSWORD ?? "DRAFT-SENDER-PASSWORD";
  const reference = resolveHmrcCtSubmissionReference(draft.utr);
  const encodedAccountsAttachment = options?.accountsAttachmentXhtml
    ? encodeInlineXbrlDocumentForCtSubmission(options.accountsAttachmentXhtml)
    : undefined;
  const encodedComputationsAttachment = options?.computationsAttachmentXhtml
    ? encodeInlineXbrlDocumentForCtSubmission(options.computationsAttachmentXhtml)
    : undefined;
  const bodyXmlWithoutIrmark = renderCt600DraftBodyXml({
    draft,
    submissionReference: reference,
    encodedAccountsAttachment,
    encodedComputationsAttachment,
  });
  const irMark = computeCt600DraftIrmark(bodyXmlWithoutIrmark);
  const bodyXml = renderCt600DraftBodyXml({
    draft,
    submissionReference: reference,
    irMark,
    encodedAccountsAttachment,
    encodedComputationsAttachment,
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${escapeXml(
    draft.filingReadiness.isReady
      ? `CT600 XML generated by Tamias for the supported filing-ready path: ${draft.filingReadiness.supportedPath}.`
      : "Draft CT600 XML generated by Tamias. Do not submit until the filing-readiness blockers are cleared.",
  )} -->
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CT-CT600</Class>
      <Qualifier>request</Qualifier>
      <Function>submit</Function>
      <CorrelationID/>
      <Transformation>XML</Transformation>
      <GatewayTest>${environment === "test" ? "1" : "0"}</GatewayTest>
    </MessageDetails>
    <SenderDetails>
      <IDAuthentication>
        <SenderID>${escapeXml(senderId)}</SenderID>
        <Authentication>
          <Method>clear</Method>
          <Role>Principal</Role>
          <Value>${escapeXml(senderPassword)}</Value>
        </Authentication>
      </IDAuthentication>
    </SenderDetails>
  </Header>
  <GovTalkDetails>
    <Keys>
      <Key Type="UTR">${escapeXml(reference)}</Key>
    </Keys>
    <TargetDetails>
      <Organisation>HMRC</Organisation>
    </TargetDetails>
    <ChannelRouting>
      <Channel>
        <URI>${escapeXml(vendorId)}</URI>
        <Product>${escapeXml(productName)}</Product>
        <Version>${escapeXml(productVersion)}</Version>
      </Channel>
    </ChannelRouting>
  </GovTalkDetails>
${bodyXml}
</GovTalkMessage>`;
}
