import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, basename } from "node:path";

type DocMetadata = {
  title: string;
  description: string;
  section?: string;
  order?: number;
};

type BlogMetadata = {
  title: string;
  publishedAt: string;
  summary: string;
  image?: string;
  tag: string;
};

type DocEntry = {
  slug: string;
  metadata: DocMetadata;
  content: string;
};

type DocMetadataEntry = Omit<DocEntry, "content">;

type BlogPost = {
  slug: string;
  metadata: BlogMetadata;
  content: string;
};

type BlogMetadataEntry = Omit<BlogPost, "content">;

function parseFrontmatter<T extends Record<string, unknown>>(fileContent: string) {
  const frontmatterRegex = /---\s*([\s\S]*?)\s*---/;
  const match = frontmatterRegex.exec(fileContent);
  const frontMatterBlock = match?.[1];
  const content = fileContent.replace(frontmatterRegex, "").trim();
  const frontMatterLines = frontMatterBlock?.trim().split("\n") || [];
  const metadata: Record<string, unknown> = {};

  for (const line of frontMatterLines) {
    const [key, ...valueArr] = line.split(": ");
    if (!key) continue;

    const trimmedKey = key.trim();
    let value = valueArr.join(": ").trim();
    value = value.replace(/^['"](.*)['"]$/, "$1");
    metadata[trimmedKey] =
      trimmedKey === "order" ? Number.parseInt(value, 10) : value;
  }

  return { metadata: metadata as T, content };
}

function readMdxEntries<T extends Record<string, unknown>>(dir: string) {
  return readdirSync(dir)
    .filter((file) => extname(file) === ".mdx")
    .sort((a, b) => a.localeCompare(b))
    .map((file) => {
      const rawContent = readFileSync(join(dir, file), "utf-8");
      const { metadata, content } = parseFrontmatter<T>(rawContent);

      return {
        slug: basename(file, extname(file)),
        metadata,
        content,
      };
    });
}

const rootDir = join(import.meta.dir, "..");
const docsDir = join(rootDir, "src", "site", "content", "docs");
const postsDir = join(rootDir, "src", "site", "content", "updates");
const outputPath = join(rootDir, "src", "site", "generated", "content-manifest.ts");

const docs = readMdxEntries<DocMetadata>(docsDir) satisfies DocEntry[];
const blogPosts = readMdxEntries<BlogMetadata>(postsDir) satisfies BlogPost[];
const docEntries = docs.map(({ slug, metadata }) => ({ slug, metadata })) satisfies DocMetadataEntry[];
const blogEntries = blogPosts.map(({ slug, metadata }) => ({ slug, metadata })) satisfies BlogMetadataEntry[];
const docContentBySlug = Object.fromEntries(
  docs.map(({ slug, content }) => [slug, content]),
) satisfies Record<string, string>;
const blogContentBySlug = Object.fromEntries(
  blogPosts.map(({ slug, content }) => [slug, content]),
) satisfies Record<string, string>;

mkdirSync(dirname(outputPath), { recursive: true });

writeFileSync(
  outputPath,
  `// Generated by scripts/generate-site-content-manifest.ts. Do not edit directly.
export type DocMetadata = {
  title: string;
  description: string;
  section?: string;
  order?: number;
};
export type BlogMetadata = {
  title: string;
  publishedAt: string;
  summary: string;
  image?: string;
  tag: string;
};
export type DocEntry = {
  slug: string;
  metadata: DocMetadata;
  content: string;
};
export type DocMetadataEntry = {
  slug: string;
  metadata: DocMetadata;
};
export type BlogPost = {
  slug: string;
  metadata: BlogMetadata;
  content: string;
};
export type BlogMetadataEntry = {
  slug: string;
  metadata: BlogMetadata;
};

export const docEntries: DocMetadataEntry[] = ${JSON.stringify(docEntries, null, 2)};

export const docContentBySlug: Record<string, string> = ${JSON.stringify(
    docContentBySlug,
    null,
    2,
  )};

export const blogEntries: BlogMetadataEntry[] = ${JSON.stringify(blogEntries, null, 2)};

export const blogContentBySlug: Record<string, string> = ${JSON.stringify(
    blogContentBySlug,
    null,
    2,
  )};
`,
);

console.log(
  `Generated site content manifest with ${docs.length} docs and ${blogPosts.length} posts.`,
);
