// Auto-generated by scripts/generate-cluster-map.ts — do not edit manually.
// Run: bun run scripts/generate-cluster-map.ts

export const procedureClusterMap: Record<string, string> = {
  // ai
  chatFeedback: "ai",
  chats: "ai",
  insights: "ai",
  // content
  companiesHouse: "content",
  compliance: "content",
  customers: "content",
  documents: "content",
  documentTagAssignments: "content",
  documentTags: "content",
  inbox: "content",
  inboxAccounts: "content",
  uploads: "content",
  // finance
  accounting: "finance",
  bankAccounts: "finance",
  bankConnections: "finance",
  banking: "finance",
  payroll: "finance",
  reports: "finance",
  transactionAttachments: "finance",
  transactionCategories: "finance",
  transactions: "finance",
  transactionTags: "finance",
  vat: "finance",
  yearEnd: "finance",
  // invoice
  invoice: "invoice",
  invoicePayments: "invoice",
  invoiceProducts: "invoice",
  invoiceRecurring: "invoice",
  invoiceTemplate: "invoice",
  // misc
  apiKeys: "misc",
  apps: "misc",
  asyncRuns: "misc",
  institutions: "misc",
  oauthApplications: "misc",
  shortLinks: "misc",
  trackerEntries: "misc",
  trackerProjects: "misc",
  // shell
  billing: "shell",
  notifications: "shell",
  notificationSettings: "shell",
  search: "shell",
  suggestedActions: "shell",
  support: "shell",
  tags: "shell",
  widgets: "shell",
};
