export const integrations = [
  { id: "gmail", name: "Gmail", href: "https://tamias.xyz/integrations/gmail" },
  { id: "outlook", name: "Outlook", href: "https://tamias.xyz/integrations/outlook" },
  { id: "slack", name: "Slack", href: "https://tamias.xyz/integrations/slack" },
  { id: "quickbooks", name: "QuickBooks", href: "https://tamias.xyz/integrations/quickbooks" },
  { id: "xero", name: "Xero", href: "https://tamias.xyz/integrations/xero" },
  { id: "fortnox", name: "Fortnox", href: "https://tamias.xyz/integrations/fortnox" },
  { id: "whatsapp", name: "WhatsApp", href: "https://tamias.xyz/integrations/whatsapp" },
  { id: "stripe-payments", name: "Stripe Payments", href: "https://tamias.xyz/integrations/stripe-payments" },
  { id: "raycast", name: "Raycast", href: "https://tamias.xyz/integrations/raycast" },
  { id: "google-drive", name: "Google Drive", href: "https://tamias.xyz/integrations/google-drive" },
  { id: "dropbox", name: "Dropbox", href: "https://tamias.xyz/integrations/dropbox" },
  { id: "stripe", name: "Stripe", href: "https://tamias.xyz/integrations/stripe" },
  { id: "polar", name: "Polar", href: "https://tamias.xyz/integrations/polar" },
  { id: "deel", name: "Deel", href: "https://tamias.xyz/integrations/deel" },
  { id: "e-invoice", name: "E-Invoice", href: "https://tamias.xyz/integrations/e-invoice" },
  { id: "cursor-mcp", name: "Cursor", href: "https://tamias.xyz/mcp/cursor" },
  { id: "claude-mcp", name: "Claude", href: "https://tamias.xyz/mcp/claude" },
  { id: "perplexity-mcp", name: "Perplexity", href: "https://tamias.xyz/mcp/perplexity" },
  { id: "raycast-mcp", name: "Raycast AI", href: "https://tamias.xyz/mcp/raycast" },
  { id: "chatgpt-mcp", name: "ChatGPT", href: "https://tamias.xyz/mcp/chatgpt" },
  { id: "opencode-mcp", name: "OpenCode", href: "https://tamias.xyz/mcp/opencode" },
  { id: "zapier-mcp", name: "Zapier", href: "https://tamias.xyz/mcp/zapier" },
  { id: "copilot-mcp", name: "Microsoft Copilot", href: "https://tamias.xyz/mcp/copilot" },
  { id: "n8n-mcp", name: "n8n", href: "https://tamias.xyz/mcp/n8n" },
  { id: "make-mcp", name: "Make", href: "https://tamias.xyz/mcp/make" },
] as const;
