/**
 * Generates the procedure-to-cluster map from cluster files.
 *
 * Reads each file in api/src/trpc/routers/clusters/*.ts, extracts the
 * exported object keys, and generates _cluster-map.gen.ts.
 *
 * Convention:
 *   clusters/shell.ts  →  export const shellRouters = { billing: ..., search: ... }
 *   → { billing: "shell", search: "shell" }
 *
 * Usage: bun run scripts/generate-cluster-map.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

const CLUSTERS_DIR = resolve(import.meta.dirname ?? __dirname, "../api/src/trpc/routers/clusters");
const OUTPUT_FILE = resolve(
  import.meta.dirname ?? __dirname,
  "../api/src/trpc/routers/_cluster-map.gen.ts",
);

// Match object keys in `export const fooRouters = { key1: ..., key2: ... }`
const EXPORT_OBJECT_KEY_RE = /^\s+(\w+)\s*:/;

function extractClusterEntries(filePath: string, clusterName: string): [string, string][] {
  const source = readFileSync(filePath, "utf-8");
  const entries: [string, string][] = [];

  // Find the exported object body
  let inObject = false;
  let braceDepth = 0;

  for (const line of source.split("\n")) {
    if (!inObject) {
      if (line.includes(`export const ${clusterName}Routers`)) {
        inObject = true;
        braceDepth += (line.match(/{/g) || []).length;
        braceDepth -= (line.match(/}/g) || []).length;
      }
      continue;
    }

    braceDepth += (line.match(/{/g) || []).length;
    braceDepth -= (line.match(/}/g) || []).length;

    if (braceDepth <= 0) break;

    const match = line.match(EXPORT_OBJECT_KEY_RE);
    if (match) {
      entries.push([match[1]!, clusterName]);
    }
  }

  return entries;
}

function main() {
  const files = readdirSync(CLUSTERS_DIR).filter((f) => f.endsWith(".ts") && !f.startsWith("_"));
  const allEntries: [string, string][] = [];

  for (const file of files.sort()) {
    const clusterName = basename(file, ".ts");
    const entries = extractClusterEntries(join(CLUSTERS_DIR, file), clusterName);

    if (entries.length === 0) {
      console.warn(`⚠ No router keys found in clusters/${file} for cluster "${clusterName}"`);
      continue;
    }

    allEntries.push(...entries);
    console.log(`  ${clusterName}: ${entries.map(([k]) => k).join(", ")}`);
  }

  // Sort entries by cluster name, then key name
  allEntries.sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]));

  // Group by cluster for readability
  const grouped = new Map<string, string[]>();
  for (const [key, cluster] of allEntries) {
    if (!grouped.has(cluster)) grouped.set(cluster, []);
    grouped.get(cluster)!.push(key);
  }

  const lines = [
    "// Auto-generated by scripts/generate-cluster-map.ts — do not edit manually.",
    `// Run: bun run scripts/generate-cluster-map.ts`,
    "",
    "export const procedureClusterMap: Record<string, string> = {",
  ];

  for (const [cluster, keys] of grouped) {
    lines.push(`  // ${cluster}`);
    for (const key of keys) {
      lines.push(`  ${key}: "${cluster}",`);
    }
  }

  lines.push("};", "");

  writeFileSync(OUTPUT_FILE, lines.join("\n"));
  console.log(`\n✅ Generated ${OUTPUT_FILE} with ${allEntries.length} entries`);
}

main();
