import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const rootDir = join(import.meta.dir, "..");
const promptsDir = join(rootDir, "src", "ai", "agents", "config");
const outputPath = join(promptsDir, "generated-prompts.ts");

const files = {
  memoryTemplate: "memory-template.md",
  suggestionsInstructions: "suggestions-instructions.md",
  titleInstructions: "title-instructions.md",
} as const;

const generatedEntries = Object.entries(files).map(([exportName, fileName]) => {
  const content = readFileSync(join(promptsDir, fileName), "utf-8");
  return `export const ${exportName} = ${JSON.stringify(content)};`;
});

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generate-agent-prompts.ts. Do not edit directly.
${generatedEntries.join("\n")}
`,
);

console.log(`Generated AI prompt bundle at ${outputPath}.`);
