import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, basename } from "node:path";

type DocMetadata = {
  title: string;
  description: string;
  section?: string;
  order?: number;
};

type BlogMetadata = {
  title: string;
  publishedAt: string;
  summary: string;
  image?: string;
  tag: string;
};

type DocEntry = {
  slug: string;
  metadata: DocMetadata;
  content: string;
};

type BlogPost = {
  slug: string;
  metadata: BlogMetadata;
  content: string;
};

function parseFrontmatter<T extends Record<string, unknown>>(fileContent: string) {
  const frontmatterRegex = /---\s*([\s\S]*?)\s*---/;
  const match = frontmatterRegex.exec(fileContent);
  const frontMatterBlock = match?.[1];
  const content = fileContent.replace(frontmatterRegex, "").trim();
  const frontMatterLines = frontMatterBlock?.trim().split("\n") || [];
  const metadata: Record<string, unknown> = {};

  for (const line of frontMatterLines) {
    const [key, ...valueArr] = line.split(": ");
    if (!key) continue;

    const trimmedKey = key.trim();
    let value = valueArr.join(": ").trim();
    value = value.replace(/^['"](.*)['"]$/, "$1");
    metadata[trimmedKey] =
      trimmedKey === "order" ? Number.parseInt(value, 10) : value;
  }

  return { metadata: metadata as T, content };
}

function readMdxEntries<T extends Record<string, unknown>>(dir: string) {
  return readdirSync(dir)
    .filter((file) => extname(file) === ".mdx")
    .sort((a, b) => a.localeCompare(b))
    .map((file) => {
      const rawContent = readFileSync(join(dir, file), "utf-8");
      const { metadata, content } = parseFrontmatter<T>(rawContent);

      return {
        slug: basename(file, extname(file)),
        metadata,
        content,
      };
    });
}

const rootDir = join(import.meta.dir, "..");
const docsDir = join(rootDir, "src", "app", "docs", "content");
const postsDir = join(rootDir, "src", "app", "updates", "posts");
const outputPath = join(rootDir, "src", "generated", "content-manifest.ts");

const docs = readMdxEntries<DocMetadata>(docsDir) satisfies DocEntry[];
const blogPosts = readMdxEntries<BlogMetadata>(postsDir) satisfies BlogPost[];

mkdirSync(dirname(outputPath), { recursive: true });

writeFileSync(
  outputPath,
  `// Generated by scripts/generate-content-manifest.ts. Do not edit directly.
export type DocMetadata = {
  title: string;
  description: string;
  section?: string;
  order?: number;
};
export type BlogMetadata = {
  title: string;
  publishedAt: string;
  summary: string;
  image?: string;
  tag: string;
};
export type DocEntry = {
  slug: string;
  metadata: DocMetadata;
  content: string;
};
export type BlogPost = {
  slug: string;
  metadata: BlogMetadata;
  content: string;
};

export const docs: DocEntry[] = ${JSON.stringify(docs, null, 2)};

export const blogPosts: BlogPost[] = ${JSON.stringify(blogPosts, null, 2)};
`,
);

console.log(
  `Generated website content manifest with ${docs.length} docs and ${blogPosts.length} posts.`,
);
